# Generated by Django 4.0.4 on 2022-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
